version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-bootstrap-Change-libexec-dir.patch",
    "0002-bootstrap-Change-bash-completion-dir.patch",
    "0003-compiler-Change-LLVM-targets.patch",
    "0004-compiler-Use-wasm-ld-for-wasm-targets.patch",
    "0005-compiler-Use-aarch64-linux-gnu-gcc-to-link-aarch64-t.patch",
]
SPDX-FileCopyrightText = "rust contributors"
SPDX-License-Identifier = "TODO-Choose-a-license"
